#!/bin/bash

# Upgrade pip first (optional, but recommended for smooth installs)
pip install --upgrade pip

# Install dependencies from requirements.txt
pip install -r requirements.txt

# You can add any extra commands here if needed, for example:
# pip install some-other-package
